<?php
	if(!isset($_SESSION))
	{
		session_start();
	}	
	if(isset($_SESSION['id']))
	{
		require_once('index_user.php');
	}
	elseif(isset($_SESSION['idEmployee']))
	{
		require_once('index_employee.php');
	}
	else
	{
		require_once('index_default.php');
	}
?>